### ISSUE TITLE
Can I save  suba-perture images and how to save?

### ISSUE THREAD

**Issue by YaMeiLiu** [hahnec/plenopticam#1]
hi，Hahne! I am very interested in your project. I run plenopticam under win, and when the program executes to light field alignment 47%, it doesn't move. Can I save  sub-aperture images and how to save?

**Comment by hahnec** [comment]
Sure, extracting sub-aperture images is supposed to work fine with this beta version. I will try to reproduce your problem on a Windows machine. Can you please send a link of your light field image and calibration file which made the program stop working? Then will have a look into that.

**Comment by hahnec** [comment]
Closing, as I cannot reproduce this issue due to lack of response. However, I suspect that there was a problem with the white image calibration file you provided to the app. Please re-open if a similar issue comes up.
