### ISSUE TITLE
Best application to view 3D model

### ISSUE THREAD

**Issue by jamesstringerparsec** [hahnec/plenopticam#12]
Hey man! Awesome updates!!!!!

I'm very excited to view the 3D point cloud data but I'm having a hard time finding a free (or paid) Windows application that will do it.  

Do you have any ideas?

**Comment by hahnec** [comment]
Thanks James! 
Long story short: [Blender](https://www.blender.org/) is the way to go.

You can use Blender to import a *.ply file which contains the point cloud data from PlenoptiCam. With version 0.6.1, the data needs to be re-scaled in Blender (z-translation ~200m, z-scale ~200 works for me). Besides, RGB colors are yet not shared with the depth data. These features may be covered in an upcoming release. I hope the current stage helps you with your projects anyways.

**Comment by hahnec** [comment]
Hi James,

I just wanted to let you know that with [v0.6.4](https://github.com/hahnec/plenopticam/releases/tag/v0.6.4-beta), important improvements have been made with regards to scaling depth (along Z axis) and colors in point clouds (using [meshlab](https://www.meshlab.net/#download)). I would therefore rather recommend [meshlab](https://www.meshlab.net/#download) for colored point clouds.

**Comment by jamesstringerparsec** [comment]
Hey man! I tried a file last night and it didn't come out at all how I thought it would, I will try again today but did you test the windows release?

**Comment by jamesstringerparsec** [comment]
I also tried to install the new version on a different PC to see if the results would be the same and I got a windows defender warning 
![image](https://user-images.githubusercontent.com/38541878/97467733-c8aa3300-1944-11eb-87b4-879f8da0181b.png)

**Comment by hahnec** [comment]
That's interesting. The apps were bundled using Travis and when installing and running things on my Windows 10.0 Build 17763, everything came out as expected without notifications about malicious software. This is probably due to missing digital signatures. Which Windows version are you running? If you cannot increase the trust level, you can alternatively install via pip on the command line, e.g.:
```
pip3 install plenopticam==0.6.4
```
and then run plenopticam's gui from your environment via:
```
plenopticam -g
```

Is the ply file present in the output folder? If so, what makes you think it is unexpected?

**Comment by jamesstringerparsec** [comment]
Hey man, I'm sorry that I left this issue open for so long.  I installed again and I got no virus warning, and I tried a new file and the depth map worked! Awesome!

**Comment by jamesstringerparsec** [comment]
Hi man, do you know why this imports to meshlab in an odd cone shape (essentially looks like two cones touching point to point)?  I made sure to have depth data before and after the focal plane, so perhaps this is why?
[depth.zip](https://github.com/hahnec/plenopticam/files/5654430/depth.zip)

**Comment by hahnec** [comment]
Heya! The data in your file seems to contain a bunch of noisy depth samples that either converge to or diverge from a point at zero depth. At this stage, I can only speculate on what is causing this. Do the corresponding sub-aperture images appear to be generally noisy? Does the pfm file look noisy?
