### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by jhss** [hahnec/plenopticam#14]
When I ran `sudo python3 setup.py install`,

>  No module named 'color_space_converter'

came out in the /plenopticam/misc/data_proc.py line 26.

I searched 'color_space_converter' module on the Internet, but I couldn't find it.

How can I solve this problem?

**Comment by hahnec** [comment]
When using setuptools, it is important to install required packages in advance. With Python3, this can be done via requirement files. Did you run ``$ python3 -m pip install -r requirements.txt`` before using the ``$ python3 setup.py install`` command?

**Comment by jhss** [comment]
Yes. I ran `$ python3 -m pip install -r requirements.txt` and subsequently `$ python3 setup.py instal`.

**Comment by hahnec** [comment]
I haven't encountered this issue and couldn't reproduce your problem with a new Python environment. The issue may be related to your local system. What happens if you install from PyPI via `pip install plenopticam`?

**Comment by jhss** [comment]
I can run plenopticam when I install by using `pip install plenopticam`.
Maybe, cloning the repository might have some errors.

Thank you very much!!

**Comment by hahnec** [comment]
Great :)
