### ISSUE TITLE
Calibration data

### ISSUE THREAD

**Issue by jhss** [hahnec/plenopticam#15]
I would like to test 'Plenopticam', but I don't have calibration data.

While searching on the Internet, I can only find lfp raw images without calibration data.

Would you let me know where can I get lfp raw images including calibration data?

It doesn't matter if the number of raw images is small.

**Comment by hahnec** [comment]
As stated in the [README documentation](https://github.com/hahnec/plenopticam/blob/master/README.rst) on the repo's main page, you can find links for two types of datasets:

1. [Lytro Illum (INRIA)](https://www.irisa.fr/temics/demos/IllumDatasetLF/index.html)
2. [Custom-built Plenoptic Camera (OPEX)](https://ndownloader.figshare.com/files/5201452)

I am sure you'll figure out how to pass them to the program. Please open an issue only when you come across a problem that you think might be undocumented. Hope you enjoy the work. Thanks!
