### ISSUE TITLE
sub-apertures data format

### ISSUE THREAD

**Issue by jhss** [hahnec/plenopticam#16]
Hi

I got sub-apertures data, named by j_i.png

I would like to know what's the meaning of (j, i)

Can I explain 'j' as a vertical index of a camera position and 'i' as a horizontal index of a camera position?

**Comment by hahnec** [comment]
Hi Ju,

I am glad you made some progress with your project. You are right. The indices in the filename reflect the viewpoint position within the array. Here, _j_ is the vertical and _i_ the horizontal index just as in a matrix. The numbers in _j_,_i_ start to count from zero and rely on the maximum number of viewpoints being extracted. For example, _j=3_ and _i=3_ correspond to the central view in a 7x7 viewpoint array. I hope this helps in getting a better understanding of the data.

Best,
Chris
