### ISSUE TITLE
Upgrade SciPy from version 1.4.1

### ISSUE THREAD

**Issue by toth2peter** [hahnec/plenopticam#18]
Currently SciPy version 1.4.1 is required (introduced in this commit: https://github.com/hahnec/plenopticam/commit/0d67816b9b4e06ab567df3ec2847c83e0af5b179) which is a bit undesirable
https://github.com/hahnec/plenopticam/blob/18f54f1701b0d31d6984bee436f6e0ae7fd34df8/requirements.txt#L2

It would be great if this version requirement was removed - release 1.6.0 might have solved the issue.
In case the issue is still there.. is it an issue which could be fixed at this repository?
If you can provide some details about it @hahnec I might try to fix it. Cheers.

**Comment by hahnec** [comment]
I will review this version constraint in an upcoming release. Did you encounter any problems with scipy being 1.4.1?

**Comment by toth2peter** [comment]
Thanks for fixing this - closing the issue now.

I did not encounter any problems with scipy 1.4.1 but just wanted to use the newer version in the rest of my project.

**Comment by chunibyo-wly** [comment]
hello, thanks for your contribution.
I notice that your setupfile alse need scipy versions equal to 1.4.1, shout this be removed?

https://github.com/hahnec/plenopticam/blob/8cc0c1cf8acc346deaee26e252933dcfdaca14a1/setup.py#L93-L94
