### ISSUE TITLE
About the use of the Lytro Illum camera

### ISSUE THREAD

**Issue by backkon** [hahnec/plenopticam#19]
About the use of the Lytro Illum camera, I have a little question to ask you. Often, when I take a picture and look at it, there is an error mark (a cross), it cannot be displayed properly. What is the reason for this and how to avoid it? Looking forward to your reply!

**Comment by hahnec** [comment]
Hi @backkon, 

Thanks for getting back with this. Can you please post a screenshot showing the error mark? I will have a look at it.

**Comment by backkon** [comment]
Like this, I took three pictures, and when I looked back, I found that the first two were unavailable for viewing, and the last one was ok. Usually, when I take some pictures, only the last picture can be viewed.
![1](https://user-images.githubusercontent.com/31430570/118917089-b0dae080-b962-11eb-862c-87f8474d270b.jpg)
![2](https://user-images.githubusercontent.com/31430570/118917093-b2a4a400-b962-11eb-9cdf-a0e84a7d2003.jpg)
![3](https://user-images.githubusercontent.com/31430570/118917095-b2a4a400-b962-11eb-802a-0e10f7396d6c.jpg)

**Comment by hahnec** [comment]
Thanks for posting the images showing the white cross. This phenomenon is clearly related to the Lytro camera and its firmware. As it has nothing to do with the code in this repo, I cannot comment or speculate on the reasoning behind it.
