### ISSUE TITLE
Program stops working

### ISSUE THREAD

**Issue by hongyann** [hahnec/plenopticam#2]
![TIM图片20190731184250](https://user-images.githubusercontent.com/53265348/62205905-20b15d00-b3c3-11e9-8db1-26adb3ea4f8a.png)
![TIM图片20190731184259](https://user-images.githubusercontent.com/53265348/62205918-28710180-b3c3-11e9-8a3f-d2499f453372.png)

Hello, I want to ask some help. My original data is from Lytro Illum. The setting part is shown in the figure. Micro image  patch size: 7; refocusing range: -2, 4.  But  After the progress bar of Light filed aligment  reaches 76%, it stoped.  I am confused .  Can you give me some suggestions?

**Comment by hahnec** [comment]
Sure! Your probably found a bug :) Can you pls provide a link to your *.lfr and *.tar file? Then I can reproduce the issue on my side.

**Comment by hongyann** [comment]
I don't know how to creat a link about  *.lfr and *.tar file. Could you provide your email address to me ? Thank you!

**Comment by hongyann** [comment]
caldata-B5143100560.tar
<https://drive.google.com/file/d/12YpunJQLVhqfDcn48T96GkaI2AeBmJiN/view?usp=drive_web>
 IMG_3780.LFR
<https://drive.google.com/file/d/1G7_z_Dn-bpw3ysWX039XUaiXwUfIdnhj/view?usp=drive_web>

These are my .tra file and .lfr file. Please try it on your computer.
Thanks!

hahnec <notifications@github.com> 于2019年8月1日周四 上午12:59写道：

**Comment by hahnec** [comment]
hey hongyann,

i have good news! i was able to reproduce the issue on my machine and did a fix which made the program run through without errors. your images revealed a problem in my centroid sort algorithm which i never encountered with my data. so, thanks for providing yours!

as of now, the fixed version is only available in the develop branch (until i make a new release). to get this working on your side, you need to clone/download from the develop branch which is found here: 

https://github.com/hahnec/plenopticam/tree/develop

then, ``cd`` to the download directory, install with ``python3 setup.py install`` and run the tool with ``plenopticam -g`` from the command line. let me know if you come across further issues. 

on a side note: with this version, i have added a feature to monitor errors by saving a file (_err_log.txt_) to the output folder next to your lfr file. this error report can be copy/pasted here and may help to trace issue in future.

**Comment by hahnec** [comment]
hey hongyann,

i have good news! i was able to reproduce the issue on my machine and did a fix which made the program run through without errors. your images revealed a problem in my centroid sort algorithm which i never encountered with my data. so, thanks for providing yours!

as of now (until i make a new release), the fixed version is only available in the develop branch. to get this working on your side, you need to clone/download from the develop branch which is found here: 

https://github.com/hahnec/plenopticam/tree/develop

then, ``cd`` to the download directory, install with ``python3 setup.py install`` and run the tool with ``plenopticam -g`` from the command line. let me know if you come across further issues. 

on a side note: with this version, i have added a feature to monitor errors by saving a file (err_log.txt) to the output folder next to your lfr file. this error report can be copy/pasted here and may help to trace issues in future.

**Comment by hongyann** [comment]
the problem has been resolved. thank you!

**Comment by hahnec** [comment]
coolio

**Comment by hongyann** [comment]
I still have a question, that is, the generated refocused images are generally darker. Is this normal? or have problems with my settings?

**Comment by hahnec** [comment]
Can you pls post images/screenshots to illustrate the problem in the referenced issue #3

**Comment by hongyann** [comment]
![TIM图片20190828155649](https://user-images.githubusercontent.com/53265348/63836858-f8f6ea00-c9ac-11e9-9582-cb7aaafae42c.jpg)
![TIM图片20190828160148](https://user-images.githubusercontent.com/53265348/63836951-280d5b80-c9ad-11e9-9201-a64f798b3437.jpg)
left image is produce by your work, the right one is produce by another. I found the left image is more darker than another. Is it normal?

**Comment by hahnec** [comment]
As this issue is closed, can you please re-post your above reply in issue #3 ? Thanks
