### ISSUE TITLE
Use for LFM

### ISSUE THREAD

**Issue by sky-fly97** [hahnec/plenopticam#21]
Hello， Can I use this code for my own LFM？

**Comment by sky-fly97** [comment]
I have taken photos with my own LFM, and I have found the lens center and extracted the image composed of macro pixels. Can I use your code to generate depth map?

**Comment by sky-fly97** [comment]
![Uploading center_view.png…]()

**Comment by sky-fly97** [comment]
![Uploading 0511-10x-Mac-50-t2.png…]()

**Comment by hahnec** [comment]
Hi!

Yes, using your your custom plenoptic camera is supposed to work with this software. Besides your light-field image, you need to take a white calibration image and pass both to the paths found in PlenoptiCam‘s user interface.

Where exactly did you get stuck?

**Comment by sky-fly97** [comment]
> Hi!
> 
> Yes, using your custom plenoptic camera is supposed to work with this software. Besides your light-field image, you need to take a white calibration image and pass both to the paths found in PlenoptiCam‘s user interface.
> 
> Where exactly did you get stuck?

Hello, my light field microscope has got a 5D LF data, I wonder if I can directly use your code to generate a depth map.

**Comment by hahnec** [comment]
Yup, depth map extraction is also possible. It seems that you haven't read the [README file](https://github.com/hahnec/plenopticam/blob/master/README.rst). Please follow the instructions there and only open an issue here if you encounter a problem.
