### ISSUE TITLE
White image file not found. Revise calibration path settings

### ISSUE THREAD

**Issue by MilanPolle** [hahnec/plenopticam#22]
I'm always getting this same error message, no matter if I select the Illum tar calibration file or the folder containing the calibration files. The correct white image files are all in there. I'm using an lfr image as my light field image. This is with version 0.8.0 and the Illum on the latest firmware version.

**Comment by hahnec** [comment]
Hi there! Thanks for raising this. Did you install the application via the installation wizard or using the command line (e.g., pip)?

**Comment by MilanPolle** [comment]
Hi! I used the installer.

**Comment by hahnec** [comment]
Hm, I see. I just installed everything from scratch on my machine and it worked as expected. I suppose you have double-checked whether your paths are valid? What OS are you using?

**Comment by MilanPolle** [comment]
You mean the paths to the raw image and calibration files? I’m using the UI to select them, so they should be correct.
I’m using Windows 10 64-bit Pro. In Program Files (x86)\plenoptic.info\PlenoptiCam there is only the plenopticam.exe file.

**Comment by hahnec** [comment]
It's an interesting problem, which I couldn't reproduce on my Win10. I think it's worth looking at the paths first. Do you have any special characters (e.g., spaces) in there? Can you make sure the selected paths in the entry fields actually exist?

**Comment by MilanPolle** [comment]
D:/Lytro/MyIllum/LEDLamp.lfr
C:/Lytro/B5144306140.tar

Both paths pasted in the windows explored path and working.

**Comment by hahnec** [comment]
These 2 paths look fine. What about the 3rd one (*metadata file path*) in the **Settings** window?

**Comment by MilanPolle** [comment]
That one is empty, what does it need to point to?

**Comment by hahnec** [comment]
It's okay that it's empty. So, the error doesn't seem to be linked to incorrect paths. In that case, the error message indicates that the hash value in the metadata of your light-field (*.lfp) image cannot be found in the provided calibration data (e.g., *.tar file). Can you confirm that both files come from the same Illum camera device?

**Comment by MilanPolle** [comment]
I see. I’ve double checked and the serial number of my Illum matches that of the tar file and the folder in appdata. That photo was shot with my camera.

Not sure if this helps, but I found this text in the err_log.txt file of that photo, with the timestamp of when I got the error:
(KeyError('files'),)

I’ve been working on a Lytro project with my own raw file loader, so I know about those hashes they use. I have it working for 1st gen Lytro but the Illum format is slightly different.

**Comment by hahnec** [comment]
There might be some minor difference with your Lytro Illum files (e.g., different firmware version?) than the others I have worked with. It would be helpful if you pass any of your *.lfp image with a corresponding *.tar file (I know it's huge), so I can start tracing the error on my side.

**Comment by MilanPolle** [comment]
Here are the raw photo and calibration tar that I was using:
https://drive.google.com/file/d/1V3bzqIYaOjv9EMP145DQlDi3o8pRufri/view?usp=sharing
https://drive.google.com/file/d/1mIh0UgtiKbGp76iUG3aCnwB3xF_ygIEy/view?usp=sharing

I hope you’ll be able to reproduce the problem with these.

**Comment by hahnec** [comment]
Thanks for providing your data! 

I was able to pinpoint the issue and extended the way metadata is found in tar-files. The fix is now available for you in the new [v0.8.1 release](https://github.com/hahnec/plenopticam/releases/tag/v0.8.1-beta). Please close this issue if the fix works for you and feel free to come back once you encounter further challenges.

##### In case you are interested in what the underlying problem was:

The diretory path in your tar-archive was different from those I have played with so far. As stated in my previous comment, this may be due to a different firmware version on your camera device. The commits 84dac75 and 96c11df enable to now consider the model number as a root name too.

Have you, by any chance, changed contents of your tar-file before using it?

**Comment by MilanPolle** [comment]
Thank you for fixing this so quickly! I will test it and close the ticket if it works here. I didn’t change the contents of the tar file, it is a direct export from the Lytro software.

**Comment by MilanPolle** [comment]
Working perfectly now, thanks for the fast fix. I hadn't changed the tar file.

**Comment by pithydon** [comment]
I'm having the same error with 0.9.3.

**Comment by PreyK** [comment]
Same here, 0.9.3&0.9.1

**Comment by knupouls** [comment]
Same here, but only on the majority of .LFR files, a few of them do just work...
