### ISSUE TITLE
white image file not present error

### ISSUE THREAD

**Issue by gdlesage** [hahnec/plenopticam#27]
I also have the “white image file not present” error.  Running v0.91b in windows 10, load “raw.lfp” for image and “caldata-<the camera’s serial number>.tar” for calibration source and get white image not present error.   My camera cannot be updated to version 2.0 firmware and is still on version 1.  I am able to view images and use all features in the lytro desktop software and I have used matlab lightfield toolbox to view and alter the images after importing the calibration data into the toolbox.  I suspect the problem is related to the firmware version of my camera, as experienced by users in issues 22 and 25.  My camera serial number starts with number rather than letter.

**Comment by hahnec** [comment]
Yes, this may be linked to the firmware which governs the way how metadata is represented. Can you share your tar archive and a lightfield photo so I can have a look at the root of this problem?

**Comment by hahnec** [comment]
Seems I found a way to assign your photo to a white image calibration file in your tar-archive using an alternative method. The built v0.9.2 is under way and can be found on the [release page](https://github.com/hahnec/plenopticam/releases) once finished. Let me know if this works for you.

**Comment by gdlesage** [comment]
Thanks update allowed me to load image and calibration data.   You should be aware that my camera might be a developer’s device, it has root access in adb shell and firmware is listed as factory build 49 rather than a version number.  So, my problem of loading calibration data might not apply to others.  Again thanks for your prompt fix.
