### ISSUE TITLE
Problem running Plenopticam on Ubuntu

### ISSUE THREAD

**Issue by martaaragaocoelho** [hahnec/plenopticam#28]
Plenopticam fails at Debayering stage on Ubuntu.
Already tried:
Ubuntu 18.04 with Python 3.8.10;
Ubuntu 20.04 with Pyhton 3.8.10;
Ubuntu 20.04 with Python 3.9;
Ubuntu 22.04 with Python 3.10.

Thank you

**Comment by hahnec** [comment]
An error log would be insightful. If there is no, the issue may be linked to a problem, which I raised here:

https://github.com/colour-science/colour-demosaicing/issues/42

My PR has been merged, but I am still waiting for the new release. In the meantime, you could increase your memory. Hope this helps.

**Comment by martaaragaocoelho** [comment]
Thank you for your reply.
I increased the ram memory to 18GB and it worked. 

Thank you for your support.
