### ISSUE TITLE
How to save the results in a different directory?

### ISSUE THREAD

**Issue by martaaragaocoelho** [hahnec/plenopticam#31]
Hello,

The results are saved in a folder located at the same directory as the light field file.
I want to know how I can save them on a different directory.

Thank you

**Comment by hahnec** [comment]
Hi Marta,

Changing the default target directory (where the lightfield photo resides) could be done by moving the photo to your desired location or would require you to change code. If you are interested in the latter, you can search for usages of the following function:

https://github.com/hahnec/plenopticam/blob/eb776339e0677463aa876f607ebdad8bd7d56bb7/plenopticam/misc/file_rw.py#L49
