### ISSUE TITLE
how to convert depth map to absolute distance

### ISSUE THREAD

**Issue by chenyuyi94** [hahnec/plenopticam#35]
sir，I want to measuring the dimensions of microscopic samples,like this [http://lightfield-forum.com/wordpress/wp-content/uploads/2018/12/lightfield-feature-depth-mapping-distance-measurement-2.jpg](url),could you please tell me how to convert depth map to absolute distance? thank you  very much

**Comment by hahnec** [comment]
This question was answered in [Baseline and triangulation geometry in a standard plenoptic camera](https://link.springer.com/article/10.1007/s11263-017-1036-4) published in the Int. Journal of Computer Vision (IJCV) with a preprint found [here](https://arxiv.org/abs/2010.046389). Based on these findings, I have assembled a [software tool](https://github.com/hahnec/plenoptisign/) that allows to convert disparities into meters given the plenoptic camera parameters.
