### ISSUE TITLE
image is dark 

### ISSUE THREAD

**Issue by hongyann** [hahnec/plenopticam#4]
![TIM图片20190828155649](https://user-images.githubusercontent.com/53265348/64017021-208bb500-cb5b-11e9-8b5c-f9c09ad29e43.jpg)
![TIM图片20190828160148](https://user-images.githubusercontent.com/53265348/64017022-21bce200-cb5b-11e9-8e55-8d2fba90d5ca.jpg)

left image is produce by your work, the right one is produce by another. I found the left image is more darker than another. Is it normal?  or  has errors with my setting?

**Comment by hahnec** [comment]
hi @hongyann ,

can you try to tick/untick the auto-contrast option in the settings window? does this improve the image brightness? let me know if this doesn't help.

**Comment by hongyann** [comment]
![2019-09-04 11-11-39屏幕截图](https://user-images.githubusercontent.com/53265348/64223095-25f35180-cf05-11e9-8443-cffc6ce2fd4d.png)
left one produced without auto-contrast, and the right one was ticked  the auto-contrast option. the right image looks better. But I still think that the color of the picture is a bit distorted, that is, the generated picture looks color abnormal compared to the color observed by the human eyes.

**Comment by hahnec** [comment]
I absolutely agree. The problem lies in the colour metric handling of plenopticam which I yet covered only rudimentary. When I take your screenshot and do simple auto-white-balancing and auto-contrast in GIMP, I get something similar to your reference image (see below: left plenopticam+GIMP, right: other)

![issue4](https://user-images.githubusercontent.com/33809838/64278263-9d989f00-cf4c-11e9-8ec3-883068472366.png)

May I ask what software you used to generate the better looking reference images?

**Comment by hongyann** [comment]
the software I used  is lytro power tool.

**Comment by hahnec** [comment]
That explains it :) I have added a new automatic white balance procedure similar to that used in GIMP. You can use it by downloading the master branch and installing via 'python setup.py install'. 

I will also implement some histogram equalization in the upcoming days and expect further improvements from this. Keep you updated

**Comment by hongyann** [comment]
I have tried to download using  'python setup.py install' ， but there have been some problems during the installation process, I have not solved it.  thanks for your answers, I will try it again.

**Comment by hahnec** [comment]
The install might have failed as your environment was missing the tiff lib. I have now implemented a workaround using pillow in case the tiff lib is not present. 

I also added a first histogram equalization method to combat the dark image areas in the output images. You can use this method by ticking the contrast option in the current version of the develop branch (see below) and install it as you tried before.

https://github.com/hahnec/plenopticam/tree/develop

Hope this helps.

**Comment by hongyann** [comment]
with your develop branch, the produced image is better than before(left : before,  right: produced now).  thank you very much. and it will be perfect if you develop the color setting similar to our eyes.
![2019-09-16 16-08-05屏幕截图](https://user-images.githubusercontent.com/53265348/64942660-3cea5a00-d89c-11e9-8a32-16f0b3925fcf.png)

when I process  a stack of light-field images , I  have a another question, that's how can I change the setting of plenopticam , for example: refocusing range, contrast automation. I have not found these settings in   plenopticam  -h .

**Comment by hahnec** [comment]
That's fantastic news! I pushed another update to the develop branch adding refocusing range options to the command line (use `-h` after re-install for details) as I was facing the same problem as you. Let me know if this works for you.

> color setting similar to our eyes

Can u pls tell more about what you mean by this?

Best
Chris

**Comment by hongyann** [comment]
It works !  so cool !   
 I am sorry that I have  given you a fuzzy suggestion.  You just ignore it. 
thanks for your answers. hope you can develop more and more excellent works.
best wishes!

**Comment by hahnec** [comment]
I am glad it worked for you. On a last note, I want you to know that all branches now feature histogram matching when contrast automation is ticked which results in more natural contrast. I added this feature yesterday. Thanks for sharing your experience which helped improve the software and please get back if you come across new issues.

Best,
Chris
